name: Pull request workflow

on: pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Git repository
        uses: actions/checkout@v4
      - name: Using Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build the Project
        run: mvn clean install